import mongoose from "mongoose";
const MobileSchema = mongoose.Schema({
  mobilename: String,
  displaysize: String,
  displaytype: String,
  resolution: String,
  hdr: String,
  screentobodyratio: String,
  ppi: String,
  refreshrate: String,
  screenprotection: String,
  dustwaterresistance: String,
  brightness: String,
  os: String,
  chipset: String,
  processorcore: String,
  gpu: String,
  wideangle: String,
  ultrawide: String,
  depth: String,
  macro: String,
  telephoto: String,
  frontcamera: String,
  ramvariant1: String,
  ramvariant2: String,
  ramvariant3: String,
  ramvariant4: String,
  storagetype: String,
  memorycardoption: String,
  expandableoption: String,
  batterycapacity: String,
  batteryspeed: String,
  fingerprint: String,
  facelock: String,
  bluetooth: String,
  port: String,
  nfc: String,
  fiveg: String,
  stereo: String,
  jack: String,
  frontimage: String,
  backimage: String,
  leftimage: String,
  rightimage: String,
});
export default mongoose.model("MOBILEDATA", MobileSchema);
